### ISSUE TITLE
PostMessage and LocalStorage errors

### ISSUE THREAD

**Issue by wrgoto** [pixelplicity/shoutout-react#1]
Hi, I'm seeing errors populate the console when embedding your wall.

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://platform.shoutout.so') does not match the recipient window's origin ('http://localhost:3001').
B @ iframeResizer.js:12
d @ iframeResizer.js:12
i @ iframeResizer.js:12
(anonymous) @ iframeResizer.js:12
(anonymous) @ embed.js:18
r @ embed.js:3
i.onload.i.onreadystatechange @ embed.js:42
load (async)
(anonymous) @ embed.js:35
(anonymous) @ embed.js:1
```

```
index.js:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://stats.shoutout.so/js/index.js:1:77
    at https://stats.shoutout.so/js/index.js:1:1346
(anonymous) @ index.js:1
(anonymous) @ index.js:1
```

**Comment by sudhakar-selva** [comment]
any update on this? 
sometimes wall is not loading when embeded in our site, In console, it showing following error . 
`iframeResizer.js:12 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://platform.shoutout.so') does not match the recipient window's origin ('https://tfs.np.razorpay.in').`
> used embed code provide in the dashboard
